import { TrackVolNaturalRequestMatches } from '../../../src/music/volume/types';

export const naturalRequestSharedCases = [
  {
    messageContent: 'raise the volume to 6.5',
    matches: [
      '',
      'raise the volume',
      undefined,
      undefined,
      undefined,
      undefined,
      'to',
      undefined,
      '6.5',
      undefined,
      undefined,
      '',
    ] as TrackVolNaturalRequestMatches[0],
    index: 0,
  },
  {
    messageContent: 'bring the volume up until 4.4',
    matches: [
      '',
      undefined,
      'bring the volume up',
      undefined,
      undefined,
      undefined,
      'until',
      undefined,
      '4.4',
      undefined,
      undefined,
      '',
    ] as TrackVolNaturalRequestMatches[0],
    index: 0,
  },
  {
    messageContent: 'make the volume higher until 3',
    matches: [
      '',
      undefined,
      'make the volume higher',
      undefined,
      undefined,
      undefined,
      'until',
      undefined,
      '3',
      undefined,
      undefined,
      '',
    ] as TrackVolNaturalRequestMatches[0],
    index: 0,
  },
  {
    messageContent: 'lower the volume until 5',
    matches: [
      '',
      undefined,
      undefined,
      'lower the volume',
      undefined,
      undefined,
      'until',
      undefined,
      '5',
      undefined,
      undefined,
      '',
    ] as TrackVolNaturalRequestMatches[0],
    index: 0,
  },
  {
    messageContent: 'reduce the volume to 5',
    matches: [
      '',
      undefined,
      undefined,
      'reduce the volume',
      undefined,
      undefined,
      'to',
      undefined,
      '5',
      undefined,
      undefined,
      '',
    ] as TrackVolNaturalRequestMatches[0],
    index: 0,
  },
  {
    messageContent: 'bring the volume down to 5',
    matches: [
      '',
      undefined,
      undefined,
      undefined,
      'bring the volume down',
      undefined,
      'to',
      undefined,
      '5',
      undefined,
      undefined,
      '',
    ] as TrackVolNaturalRequestMatches[0],
    index: 0,
  },
  {
    messageContent: 'increase the volume to 5.45',
    matches: [
      '',
      'increase the volume',
      undefined,
      undefined,
      undefined,
      undefined,
      'to',
      undefined,
      '5.45',
      undefined,
      undefined,
      '',
    ] as TrackVolNaturalRequestMatches[0],
    index: 0,
  },
  {
    messageContent: 'increase the volume by 5.45',
    matches: [
      '',
      'increase the volume',
      undefined,
      undefined,
      undefined,
      undefined,
      undefined,
      'by',
      '5.45',
      undefined,
      undefined,
      '',
    ] as TrackVolNaturalRequestMatches[0],
    index: 0,
  },
  {
    messageContent: 'make the volume 5',
    matches: [
      '',
      undefined,
      undefined,
      undefined,
      undefined,
      'make the volume',
      undefined,
      undefined,
      '5',
      undefined,
      undefined,
      '',
    ] as TrackVolNaturalRequestMatches[0],
    index: 0,
  },
  {
    messageContent: 'make the volume to 5',
    matches: [
      '',
      undefined,
      undefined,
      undefined,
      undefined,
      'make the volume',
      'to',
      undefined,
      '5',
      undefined,
      undefined,
      '',
    ] as TrackVolNaturalRequestMatches[0],
    index: 0,
  },
  {
    messageContent: 'make the volume to 5 for song 4',
    matches: [
      '',
      undefined,
      undefined,
      undefined,
      undefined,
      'make the volume',
      'to',
      undefined,
      '5',
      '4',
      undefined,
      '',
    ] as TrackVolNaturalRequestMatches[0],
    index: 0,
  },
  {
    messageContent: 'make the volume to 5 for the 4th track',
    matches: [
      '',
      undefined,
      undefined,
      undefined,
      undefined,
      'make the volume',
      'to',
      undefined,
      '5',
      undefined,
      '4',
      '',
    ] as TrackVolNaturalRequestMatches[0],
    index: 0,
  },
];
